function data=scope_data()

data=struct('style',[],...
            'string',[],...
            'position',[],...
            'title',[],...
            'value',[],...
            'bounds',[],...
            'ticks',[],...
            'color',[],...
            'displayonly',0);

return;

