function def=scope_defines()

D1=25;
D2=50;
D3=100;

% alpha scales the gui
alpha=1.4;

D1=alpha*D1;
D2=alpha*D2;
D3=alpha*D3;

def=struct('defaultcolor',[0.702, 0.702, 0.702],...
           'yellow',[1, 1, 0.33],...
           'XGUI',0,...
           'YGUI',0,...
           'GUIWIDTH',2*D1+3*D3/1.5+D3,...
           'GUIHEIGHT',6.5*D3,... %1.5*650,...
           'XMARGIN',D1,...
           'YMARGIN',D1,...
           'POPUPWIDTH',D3,...
           'POPUPHEIGHT',D3/7,...
           'TITLEWIDTH',D3,...
           'TITLEHEIGHT',D3/7,...
           'SLIDERWIDTH',D3,...
           'SLIDERHEIGHT',D3/7,...
           'EDITWIDTH',D3,...
           'EDITHEIGHT',D3/7,...
           'BUTTONWIDTH',20,...
           'BUTTONHEIGHT',D3/7,...
	   'CHECKBOXWIDTH',D2,...
	   'CHECKBOXHEIGHT',D3/7,...
           'tag_chan_signal', 1,...
           'tag_chan_offset', 2,...
           'tag_chan_offset_2', 3,...
           'tag_chan_range', 4,...
           'tag_chan_title', 5,...
	   'tag_chan_signal_enable', 6,...
           'tag_chan_offset_zeroise', 7,...
           'tag_meas_title', 8,...
           'tag_meas_rate', 9,...
           'tag_meas_aa', 10,...
	   'tag_meas_frame', 11,...
	   'tag_meas_windowing', 12,...
	   'tag_meas_nframes', 13,...
	   'tag_meas_time', 14,...
	   'tag_meas_current', 15,...
	   'tag_save_last', 16,...
	   'tag_generator', 17,...
	   'tag_inst', 18,...
	   'tag_avg', 19,...
	   'tag_stop', 20,...
	   'tag_exit', 21,...
	   'tag_scope_id', 22,...
	   'tag_scope_type', 23,...
	   'tag_scope_scale', 24,...
	   'tag_scope_hold', 25,...
	   'tag_scope_freeze', 26,...
	   'tag_scope_title', 27,...
	   'tag_scope_adc0', 28,...
	   'tag_scope_adc1', 29,...
	   'tag_scope_adc2', 30,...
	   'tag_scope_adc3', 31,...
	   'tag_scope_enc0', 32,...
	   'tag_scope_enc1', 33,...
	   'tag_scope_enc2', 34,...
	   'tag_scope_enc3', 35,...
	   'tag_trig_title', 36,...
	   'tag_trig_chan_signal', 37,...
	   'tag_trig_onoff', 38,...
	   'tag_trig_level', 39,...
	   'tag_trig_preroll', 40,...
	   'tag_trig_lowpass', 41,...
	   'tag_load_settings', 42,...
           'tag_save_settings', 43,...
           'tag_overload_title', 44,...
           'tag_led_adc0', 45,...
           'tag_led_adc1', 46,...
           'tag_led_adc2', 47,...
           'tag_led_adc3', 48,...
           'tag_led_inst', 49,...
           'tag_led_avg', 50,...
           'tag_copyright_title', 51,...
           'tag_gen_chan_signal', 52,...
           'tag_gen_chan_offset', 53,...
           'tag_gen_chan_offset_2', 54,...
           'tag_gen_chan_title', 55,...
           'tag_gen_chan_ampl', 56,...
           'tag_gen_chan_ampl_2', 57,...
           'tag_gen_chan_freq', 58,...
           'tag_gen_chan_freq_2', 59,...
           'tag_gen_chan_time', 60,...
           'tag_gen_chan_time_2', 61,...
	   'tag_gen_chan_signal_enable', 62,...
           'tag_gen_chan_offset_zeroise', 63,...
           'tag_gen_chan_ampl_focus', 64,...
           'tag_gen_chan_freq_focus', 65,...
           'tag_gen_link', 66,...
           'tag_gen_power', 67,...
           'tag_gen_exit', 68);

return;



